### ISSUE TITLE
Literally does not work

### ISSUE THREAD

**Issue by s1nistr4** [goolord/alpha-nvim#178] opened 2023-02-09 23:52 UTC
1. Install Neovim
2. Install this using Packer through Lua, copying and pasting the code from the docs
3. Doesn't work

This does not work at all on a fresh install of the latest version of Neovim provided by Fedora (0.8.3)

**Comment by jiriks74** [comment] 2023-02-10 01:50
I can confirm. I use this in AstroNvim. 
Commit 704ff0f is the one from which stuff doesn't work.

> **Note**
> Last working commit was 21a0f25.

**Comment by flatplate** [comment] 2023-02-10 13:25
Same as @jiriks74 , using astronvim, does not work after updating. 

```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: ...share/nvim/site/pack/packer/opt/alpha-nvim/lua/alpha.lua:449: attempt to index local 'conf' (a nil value)
stack traceback:
	...share/nvim/site/pack/packer/opt/alpha-nvim/lua/alpha.lua:449: in function 'enable_alpha'
	...share/nvim/site/pack/packer/opt/alpha-nvim/lua/alpha.lua:652: in function 'start'
	/Users/ural.bayhan/.config/nvim/lua/core/autocmds.lua:141: in function </Users/ural.bayhan/.config/nvim/lua/core/autocmds.lua:127>
```

**Comment by goolord** [comment] 2023-02-10 18:56
there was a bug in an older commit but it should be fixed in HEAD, I can't reproduce this with the debug config or by installing from github with Lazy.nvim 😕

**Comment by goolord** [comment] 2023-02-10 19:03
yeah I'm pretty convinced that this is caused by using an older revision of `alpha`, I can't reproduce this with the latest commit at all

**Comment by goolord** [comment] 2023-02-10 19:19
ah i see this is caused by some misuse of `alpha.start` in `AstroNvim`, which is probably why the steps you said to take to reproduce don't work :)

i'll try to push a fix for this even tho it's (imo) an abuse of the api

**Comment by goolord** [comment] 2023-02-10 19:23
proper support for `start` with no args here https://github.com/goolord/alpha-nvim/commit/de59ce6b9e9a743e632cb3b8b0e89684bc6cb207

**Closed by goolord** 2023-02-10 19:23 UTC

**Comment by mehalter** [comment] 2023-02-11 11:46
@goolord thanks for looking into this. I know I discussed this stuff with you recently when the changes to alpha came out. Just to provide some context, AstroNvim does not currently have any issues with alpha  and everything works out our end as expected! The latest release of AstroNvim uses an older version of Alpha and therefore doesn't have a problem with using `start` with no arguments. 

The upcoming release of AstroNvim is currently in an unreleased state and does use a new version of Alpha and does not call `start` with no arguments:  https://github.com/AstroNvim/AstroNvim/blob/v3/lua/core/autocmds.lua#L125-L142

We do have some interesting uses of the API and I agree that you should not have changed the API to support what AstroNvim was doing with the old release as that's not what we are doing now

**Comment by goolord** [comment] 2023-02-11 11:52
I try (and seldom succeed, lol) to avoid breaking changes, and I am kind of erring on the side of making the API as flexible as possible.
I program in statically typed languages all day at work, so sometimes when I come home I forget that polyvariadic functions exist. Very happy to be a part of your distribution, gl and thanks for the patience T~T

**Comment by mehalter** [comment] 2023-02-11 12:06
Thanks! Sorry for the unnecessary noise here. This plugin has definitely been going great :)
