### ISSUE TITLE
Alpha causes error when running PackerSync in a narrow window

### ISSUE THREAD

**Issue by JulesNP** [goolord/alpha-nvim#158] opened 2022-11-22 22:34 UTC
When using Alpha in a narrow terminal window (around 75 characters wide or less), an error occurs when trying to run `:PackerSync` from the main Alpha window:
![image](https://user-images.githubusercontent.com/44929900/203434324-e2b3bfac-764e-4a61-9d14-c5db325de977.png)

After bypassing error message by pressing enter, a second Alpha window appears, rather than the Packer window:
![image](https://user-images.githubusercontent.com/44929900/203434405-2df6e001-fcbd-452d-9539-43c0c8f64729.png)

Attempting to interact with or close the second Alpha window results in further error messages:
![image](https://user-images.githubusercontent.com/44929900/203434984-1168dfcd-7df4-4d76-bc92-95b1055a498a.png)

**Comment by goolord** [comment] 2023-02-07 06:31
can anyone reproduce this on HEAD neovim HEAD alpha-nvim? i'm not getting this issue anymore even sporadically

**Comment by ryanbyon** [comment] 2023-02-09 04:53
This can be reproduced by splitting panes on alpha dashboard by `vsp | enew` or launching NvimTree when `vim.fn.winwidth(0) < 80`. (or opening vim in very narrow window size ~10)
below is my alpha config:
```lua
local function shortcuts()
    -- snippet for setting up buffer keybindings
	return {
		{
			type = "text",
			val = {
				" New File [n]     Project [p]     Todo [t]     Settings [s]",
			},
			opts = {
				position = "center",
				hl = {
					{ "Function", 1, 19 },
					{ "Keyword", 19, 36 },
					{ "String", 36, 56 },
					{ "Number", 56, 80 },
				},
			},
		},
	}
end

local section_shortcuts = { type = "group", val = shortcuts()}

local config = {
	layout = {
		section_shortcuts,
	},
}

alpha.setup(config)
```

**Comment by goolord** [comment] 2023-02-09 06:35
fixed in https://github.com/goolord/alpha-nvim/commit/5f19b4de786b7b083d6170963b546cf0fd50f3c7

the highlighting is still messed up a little. not sure what's up with that

**Closed** 2023-02-09 06:35 UTC

**Comment by goolord** [comment] 2023-02-09 06:54
fixed the highlighting in https://github.com/goolord/alpha-nvim/commit/0349fc0aa0c1d940ec3be395cb110483b416bc84

note: rn only one of the alpha windows can be active at a time, so if you :split: you may notice that one of the windows will be uninteractable; this is intended but i'm working on a workaround

**Comment by ryanbyon** [comment] 2023-02-09 07:58
Thanks for the quickfix!
Yeah I never split pane on alpha screen unless opening NvimTree, but just wanted to give you alternative way to reproduce. :)
