### ISSUE TITLE
cd command shows error message

### ISSUE THREAD

**Issue by comiluv** [goolord/alpha-nvim#179] opened 2023-02-10 08:42 UTC
please *read the documentation* before asking questions about configuration or creating a feature request

for bugs: provide the expected behavior and the actual behavior, and screenshots if you want to be nice
* Description
changing directory using ```:cd``` command shows error messages
* Steps to reproduce
1. Setup alpha-nvim using lazy:
```lua
{
    'goolord/alpha-nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function ()
        require'alpha'.setup(require'alpha.themes.startify'.config)
    end
}
```
2. ```nvim```
3. ```:e tmp```
4. ```:cd .```
5. See error
* Expected
:cd command changes current working directory to . without any error messages
* Actual behavior
```
Error detected while processing DirChanged Autocommands for "*":
Error executing lua callback: ...ij/AppData/Local/nvim-data/lazy/alpha-nvim/lua/alpha.lua:598: attempt to index local 'alpha_prime' (a nil value)
stack traceback:
        ...ij/AppData/Local/nvim-data/lazy/alpha-nvim/lua/alpha.lua:598: in function 'redraw'
        .../nvim-data/lazy/alpha-nvim/lua/alpha/themes/startify.lua:235: in function <.../nvim-data/lazy/alpha-nvim/lua/alpha/themes/startify.lua:235>
```
* Environment
Windows 11
Neovim 0.8.3
lazy.nvim [e285559](https://github.com/folke/lazy.nvim/commit/e28555950f8ceb52e86533df6df333dcd55fba04)
alpha-nvim [0349fc0](https://github.com/goolord/alpha-nvim/commit/0349fc0aa0c1d940ec3be395cb110483b416bc84)

**Comment by kevmuko** [comment] 2023-02-10 17:08
I'm also experiencing the same issue (originally caused by nvim-tree's cd)...

Pinning to last working commit for now 21a0f25

**Comment by goolord** [comment] 2023-02-10 18:49
are you sure you're on `0349fc0` alpha? i did accidentally introduce this bug but it should already be fixed

**Comment by goolord** [comment] 2023-02-10 18:58
please try syncing and seeing if you still run into the same issue..

**Comment by goolord** [comment] 2023-02-10 19:06
nvm, i was able to reproduce

**Comment by goolord** [comment] 2023-02-10 19:12
fixed in https://github.com/goolord/alpha-nvim/commit/46f6cd41a701be55cce669d99bbf984b32e2f81a

**Closed by goolord** 2023-02-10 19:12 UTC

**Comment by bqv** [comment] 2024-12-04 20:00
I believe this happens again, on de72250, when one tab has a :tcd separate to the global cwd, and one switches between such tabs

**Comment by bqv** [comment] 2024-12-04 20:03
Nope, nevermind, my bad. Different error:

```yaml
Error detected while processing DirChanged Autocommands for "*":                                                                                                                                                                                                                
Error executing lua callback: /home/bqv/.local/share/nvim/lazy/alpha-nvim/lua/alpha.lua:626: Invalid buffer id: 1                                                                                                                                                             
stack traceback:                                                                                                                                                                                                                                                                
        [C]: in function 'nvim_buf_set_option'                                                                                                                                                                                                                                  
        /home/bqv/.local/share/nvim/lazy/alpha-nvim/lua/alpha.lua:626: in function 'draw'                                                                                                                                                                                     
        /home/bqv/.local/share/nvim/lazy/alpha-nvim/lua/alpha.lua:661: in function 'redraw'                                                                                                                                                                                   
        ...share/nvim/lazy/alpha-nvim/lua/alpha/themes/startify.lua:242: in function <...share/nvim/lazy/alpha-nvim/lua/alpha/themes/startify.lua:241>  
```
